# Generated by Django 5.2.5 on 2025-08-31 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Viagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_pais', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('tempo', models.CharField(choices=[('curta', 'Curta'), ('longa', 'Longa')], max_length=10)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImagemViagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='viagens/')),
                ('viagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='viagens.viagem')),
            ],
        ),
    ]
