# Generated by Django 5.2.5 on 2025-09-01 19:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='viagem',
            old_name='nome_pais',
            new_name='pais',
        ),
        migrations.RenameField(
            model_name='viagem',
            old_name='preco',
            new_name='valor',
        ),
        migrations.RemoveField(
            model_name='viagem',
            name='criado_em',
        ),
        migrations.RemoveField(
            model_name='viagem',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='viagem',
            name='tempo',
        ),
        migrations.AddField(
            model_name='viagem',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='viagem',
            name='data_viagem',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='viagem',
            name='tipo',
            field=models.CharField(default='turismo', max_length=50),
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_agendada', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('viagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viagens.viagem')),
            ],
        ),
        migrations.DeleteModel(
            name='ImagemViagem',
        ),
    ]
