# Generated by Django 5.2.5 on 2025-08-31 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
        ('viagens', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='criado_em',
            new_name='data_reserva',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='pais_custom',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='preco_custom',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='tempo_custom',
        ),
        migrations.AddField(
            model_name='reserva',
            name='numero_pessoas',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='viagem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='viagens.viagem'),
        ),
    ]
