# Generated by Django 5.2.5 on 2025-08-31 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_rename_criado_em_reserva_data_reserva_and_more'),
        ('viagens', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='data_reserva',
            new_name='criado_em',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='numero_pessoas',
        ),
        migrations.AddField(
            model_name='reserva',
            name='pais_custom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='preco_custom',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='tempo_custom',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='viagem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='viagens.viagem'),
        ),
    ]
